<?php

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Serialization\Yaml;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\file\Entity\File;
use Drupal\taxonomy\Entity\Term;
use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_theme().
 */
function carlson_quiz_theme() {
  return [
    'node__quiz' => [
      'render element' => 'elements',
      'base hook' => 'node',
    ],
    'node__quiz__quiz_results' => [
      'variables' => [
        'node' => NULL,
        'webform_submission' => NULL,
        'results' => NULL,
      ],
    ],
    'taxonomy_term__quiz_result_teaser' => [
      'render element' => 'elements',
      'base hook' => 'taxonomy_term',
    ],
    'taxonomy_term__quiz_result_teaser_alt' => [
      'render element' => 'elements',
      'base hook' => 'taxonomy_term',
    ],
    'paragraph__quiz_conditional_paragraph' => [
      'render element' => 'elements',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_entity_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function carlson_quiz_node_presave(EntityInterface $entity) {
  if($entity->bundle() == 'quiz' && $entity->hasField('field_quiz_questions')) {

    $elements = [];
    $numbers = [
      'zero',
      'one',
      'two',
      'three',
      'four',
      'five'
    ];
    $questions = $entity->get('field_quiz_questions')->referencedEntities();

    $settings = [
      'confirmation_type' => 'url',
      'confirmation_url' => '/node/'.$entity->id().'/results/[webform_submission:sid]',
      'form_novalidate' => true
    ];

    foreach ($questions as $question_key => $question) {
      if($question->hasField('field_quiz_question_answers')) {
        $text = $question->hasField('field_quiz_question_text') ? strip_tags($question->get('field_quiz_question_text')->value, '<a><b><div><strong><i><em><img><span><small><br>') : '';
        $help_text = $question->hasField('field_quiz_question_help_text') && !empty($question->get('field_quiz_question_help_text')->getValue()) ? '<button class="quiz--question--info-btn border-0 p-0 bg-transparent" type="button" data-toggle="popover" data-trigger="hover" data-placement="bottom" data-html="true" data-content="'.str_replace(["\r", "\n"], '', htmlspecialchars($question->get('field_quiz_question_help_text')->value)).'"><span class="sr-only">Help Text</span></button>' : '';
        $type = $question->hasField('field_quiz_question_type') && $question->get('field_quiz_question_type')->value === 'multiple' ? 'checkboxes' : 'radios';
        $answers_layout = $question->hasField('field_quiz_question_answs_layout') && !empty($question->get('field_quiz_question_answs_layout')->getValue()) ? $question->get('field_quiz_question_answs_layout')->value : 'stacked';
        $answers = $question->get('field_quiz_question_answers')->referencedEntities();
        $conditional_question = $question->hasField('field_quiz_question_cond_qn') && !empty($question->get('field_quiz_question_cond_qn')->getValue()) ? $question->get('field_quiz_question_cond_qn')->getValue() : '';
        $conditional_answers = $question->hasField('field_quiz_question_cond_answ') && !empty($question->get('field_quiz_question_cond_answ')->getValue()) ? $question->get('field_quiz_question_cond_answ')->getValue() : '';
        $limit_type = $question->hasField('field_quiz_question_limit_type') && !empty($question->get('field_quiz_question_limit_type')->getValue()) ? $question->get('field_quiz_question_limit_type')->getValue() : '';
        $limit = $question->hasField('field_quiz_question_limit') && !empty($question->get('field_quiz_question_limit')->getValue()) ? $question->get('field_quiz_question_limit')->getValue() : '';
        $multiple_choice_label = 'Select all that apply';
        $options = [];
        $options_properties = [];
        $states = [];
        $question_states = [];
        $question_attributes = [];

        // $prev_button = $question_key > 0 ? '<legend class="d-none">Prev Button</legend><a class="question-'.($question_key + 1).'-prev-button question-'.$question->id().'-prev-button quiz--question--prev btn btn-outline-primary py-3 px-4 px-sm-5" href="#edit-question-'.$questions[$question_key - 1]->id().'-title" id="question-'.$question->id().'-prev-button">Previous</a>' : '';
        // $next_button = next($questions) ? '<legend class="d-none">Next Button</legend><a class="question-'.($question_key + 1).'-next-button question-'.$question->id().'-next-button quiz--question--next btn btn-primary py-3 px-4 pl-sm-5" href="#edit-question-'.$questions[$question_key + 1]->id().'-title" id="question-'.$question->id().'-next-button">Next</a>' : '';;

        foreach ($answers as $answer_key => $answer) {
          $answer_id = $answer->id();
          $answer_text = $answer->hasField('field_quiz_answer_text') ? $answer->get('field_quiz_answer_text')->value : '';
          $answer_icon_entity = $answer->hasField('field_quiz_answer_icon') && !empty($answer->get('field_quiz_answer_icon')->target_id) ? $answer->get('field_quiz_answer_icon')->referencedEntities()[0] : null;
          $answer_icon_file = $answer_icon_entity ? $answer_icon_entity->get('field_media_file')->referencedEntities()[0] : null;
          $answer_icon_url = $answer_icon_file ? $answer_icon_file->createFileUrl() : '';
          $answer_icon = $answer_icon_url ? '<img src="'.$answer_icon_url.'" alt="" aria-hidden="true" width="38" height="38" />' : '';
          $options[$answer_id] = $answer_text.' -- '.$answer_icon;
          $answer_wrapper_classes = '';
          switch ($answers_layout) {
            case 'three_cols':
              $answer_wrapper_classes .= 'col-lg mx-lg-4';
          }
          $options_properties[$answer_id] = [
            '#wrapper_attributes' => [
              'class' => ['quiz--answer col-12 '.$answer_wrapper_classes],
            ],
            '#attributes' => [
              'class' => [
                'question-'.($question_key + 1).'-answer-'.($answer_key + 1),
                'question-'.$question->id().'-answer-'.$answer->id(),
              ]
            ]
          ];
        }

        if($conditional_question != '' && $conditional_answers != '') {
          foreach ($conditional_answers as $conditional_answer_key => $conditional_answer) {
            if($conditional_answer_key > 0) {
              $states['visible'][] = 'or';
            }
            $states['visible'][][':input[name="question_'.$conditional_question[0]['value'].'"]'] = [
              'value' => $conditional_answer['value']
            ];
          }
        }

        if(!empty($states)) {
          $question_states['visible'] = $states['visible'];
          $question_states['required'] = $states['visible'];
        }

        $question_attributes['class'] = ['mb-5', 'quiz--question', $answers_layout];
        if($type == 'checkboxes' && $limit_type !== '' & $limit !== '') {
          $question_attributes['class'][] = 'has-limit';
          $question_attributes['data-limit-type'] = $limit_type[0]["value"];
          $question_attributes['data-limit'] = $limit[0]["value"];
          if($limit_type[0]["value"] == 'up_to') {
            $multiple_choice_label = 'Select up to '.$numbers[$limit[0]["value"]].'.';
          }
          elseif ($limit_type[0]["value"] == 'at_least') {
            $multiple_choice_label = 'Select '.$numbers[$limit[0]["value"]].' or more.';
          }
          elseif ($limit_type[0]["value"] == 'exactly') {
            $multiple_choice_label = 'Select exactly '.$numbers[$limit[0]["value"]].'.';
          }
        }

        $elements['question_'.$question->id().'_title'] = [
          '#type' => 'processed_text',
          '#format' => 'rich_text',
          '#text' => '<legend class="d-none">Question Title</legend><div class="quiz--question--title-prefix text-uppercase mb-2">Question '.($question_key + 1).'</div><div class="quiz--question--title column__heading"><p class="d-inline h3">'.str_replace(["\r", "\n"], '', $text).'</p>'.$help_text.'</div>'.($type === 'checkboxes' ? '<div class="quiz--question--multiple-label">'.$multiple_choice_label.'</div>' : ''),
          '#wrapper_attributes' => [
            'class' => ['quiz--question--title-wrapper'],
          ],
          '#states' => $states,
        ];

        $elements['question_'.$question->id()] = [
          '#type' => $type,
          '#title' => $text,
          '#default_value' => '',
          '#wrapper_attributes' => $question_attributes,
          '#options' => $options,
          '#options__properties' => $options_properties,
          '#states' => $question_states,
          '#required'=> empty($states),
          '#required_error' => empty($states) ? 'Please select an answer before proceeding' : ''
        ];

        // if($prev_button !== '' || $next_button !== '') {

        //   if($prev_button !== '') {
        //     $elements['question_'.$question->id().'_prev_button'] = [
        //       '#type' => 'processed_text',
        //       '#format' => 'rich_text',
        //       '#wrapper_attributes' => [
        //         'class' => ['mb-5 mr-4 d-inline-block float-left'],
        //       ],
        //       '#text' => $prev_button,
        //       '#states' => $states,
        //     ];
        //     if(!empty($states)) {
        //       $prev_question = $questions[$question_key-1];
        //       $elements['question_'.$prev_question->id().'_next_button']['#states'] = $states;
        //     }
        //   }

        //   if($next_button !== '') {
        //     $elements['question_'.$question->id().'_next_button'] = [
        //       '#type' => 'processed_text',
        //       '#format' => 'rich_text',
        //       '#wrapper_attributes' => [
        //         'class' => ['mb-5 d-inline-block'],
        //       ],
        //       '#text' => $next_button,
        //     ];
        //   }
        // }
      }
    }

    $elements['results'] = [
      '#type' => 'hidden',
      '#title' => 'Results',
    ];

    $elements['results_analyze'] = [
      '#type' => 'hidden',
      '#title' => 'Results Analyze',
    ];

    // contact fields

    $elements['markup'] = [
      '#type'=> 'webform_markup',
      '#admin_title' => 'Title',
      '#wrapper_attributes' => [
        'class' => ['w-100'],
      ],
      '#markup' => "
        <h3 style='font-size: 2.4rem; font-weight: bold'>Receive results via email (optional)</h3>

        <p>In addition to seeing your results on the next page, you can also receive information about our master's degrees via email. Enter your contact details below to receive more information.</p>
      "
    ];

    $elements['firstname'] = [
      '#type' => 'textfield',
      '#title' => 'First Name',
      '#placeholder' => 'First Name',
      '#required' => true,
      '#required_error' => 'Please enter your first name'
    ];

    $elements['lastname'] = [
      '#type' => 'textfield',
      '#title' =>'Last Name',
      '#placeholder' => 'Last Name',
      '#required' => true,
      '#required_error' => 'Please enter your last name'
    ];

    $elements['email'] = [
      '#type' => 'email',
      '#title' => 'Email',
      '#placeholder' => 'Email',
      '#required' => true,
      '#required_error' => 'Please enter your email address'
    ];

    $elements['phone'] = [
      '#type' =>'tel',
      '#title' => 'Phone',
      '#placeholder' => 'Mobile Phone',
      '#required' => true,
      '#required_error' => 'Please enter a valid phone number'
    ];
    $elements['country'] = [
      '#type' => 'select',
      '#title' => 'Country',
      '#options' => 'country_codes_us_first_',
      '#required' => true
    ];

    $elements['zip'] = [
      '#type' => 'textfield',
      '#title' => 'Postal Code',
      '#placeholder' => 'Postal Code',
      '#required' => true
    ];

    $elements['student_type'] = [
      '#type' => 'select',
      '#title'=> 'I am an',
      '#options' => [
        'international' => 'International student',
        'military' => 'U.S. military member or veteran'
      ]

    ];

    $elements['work_experience'] = [
      '#type' => 'select',
      '#title'=> 'Work Experience',
      '#options'=> [
        'undergraduate' => 'Current undergraduate student',
        '0-2' => '0-2 years full-time experience',
        '2+' => '2+ years full-time experience'
      ]
    ];
    
    $elements['disclosure'] = [
      '#type' => 'webform_markup',
      '#markup' => '<p><sup>By submitting this form, I am agreeing that Minnesota Carlson and its agent, </sup><a href="https://carlsonschool.umn.edu/risepoint-partnership"><sup>Risepoint</sup></a><sup>, may email me or contact me regarding educational services by telephone and/or text message utilizing automated technology or a pre-recorded message at the telephone number provided above. I understand this consent is not a condition to attend Minnesota Carlson. </sup><a href="https://privacy.umn.edu/"><sup>University of Minnesota privacy statement</sup></a><sup>. </sup><a href="https://policies.risepoint.com/privacy-main/"><sup>Risepoint privacy policy.</sup></a><sup> </sup><a href="/node/129371"><sup>Minnesota Carlson Privacy notice.</sup></a></p>'
    ];


    // utm fields

    $elements['utm_source'] = [
      '#type' => 'hidden',
      '#title' => 'UTM Source'
    ];

    $elements['utm_medium'] = [
      '#type' => 'hidden',
      '#title' => 'UTM Medium'
    ];

    $elements['utm_term'] = [
      '#type' => 'hidden',
      '#title' => 'UTM Term'
    ];

    $elements['utm_content'] = [
      '#type' => 'hidden',
      '#title' => 'UTM Content'
    ];

    $elements['utm_campaign'] = [
      '#type' => 'hidden',
      '#title' => 'UTM Campaign'
    ];

    $elements['actions'] = [
      '#type' => 'webform_actions',
      '#title' => 'Submit button(s)',
      '#submit__label' => 'Get My Results',
      '#attributes' => [
        'class' => ['mb-5 d-inline-block']
      ]
    ];

    $webform = Webform::load('quiz_node_'.$entity->id());
    $settings += Webform::getDefaultSettings();
    $webform_title = 'Quiz: '.$entity->label();

    if(isset($webform)) {
      $webform->setElements($elements)
        ->setSettings($settings)
        ->save();
    }
    else {
      $webform = Webform::create([
        'id' => 'quiz_node_'.$entity->id(),
        'title' => $webform_title,
        'elements' => Yaml::encode($elements),
        'settings' => $settings,
      ]);
      $webform->save();
    }
    if($entity->hasField('field_quiz_webform')) {
      $entity->set('field_quiz_webform', 'quiz_node_'.$entity->id());
    }
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @param $element
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $context
 */
function carlson_quiz_field_widget_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {

  if (isset($element['subform']['#parents'])) {

    $parents_array = $element['subform']['#parents'];
    $parents = array_shift($parents_array) . '[' . implode('][', $parents_array) . ']';

    if ($element['#paragraph_type'] == 'quiz_question' || $element['#paragraph_type'] == 'quiz_conditional_paragraph') {

      if($context["items"]->count() > 1) {

        $questions = $context["items"]->getValue();
        $options = $element["subform"]["field_quiz_question_cond_qn"]["widget"]["#options"];

        foreach ($questions as $selected_question) {
          if(!empty($selected_question) && $selected_question["entity"]->hasField('field_quiz_question_text')) {
            $key = $selected_question["target_id"];
            $value = strip_tags($selected_question["entity"]->get('field_quiz_question_text')->value);
            $options[$key] = $value;
          }
        }

        $element["subform"]["field_quiz_question_cond_qn"]["widget"]["#options"] = $options;


        $question_default_value = $element["subform"]["field_quiz_question_cond_qn"]["widget"]["#default_value"];

        if(!empty($question_default_value) && $question_default_value[0] != '_none') {
          $selected_question = Paragraph::load($question_default_value[0]);
          $answers = $selected_question->get('field_quiz_question_answers')->referencedEntities();
          $options = [];
          $options[''] = '- None -';
          foreach ($answers as $answer_key => $answer) {
            $answer_id = $answer->id();
            $answer_text = $answer->get('field_quiz_answer_text')->value;
            $options[$answer_id] = $answer_text;
          }
          $element["subform"]["field_quiz_question_cond_answ"]["widget"]["#options"] = $options;
        }
        else {
          $options = [];
          $options[''] = '- None -';
          $element["subform"]["field_quiz_question_cond_answ"]["widget"]["#options"] = $options;
        }

      }

      $element['subform']['field_quiz_question_cond_answ']['#states'] = [
        'visible' => [
          'select[name="' . $parents . '[field_quiz_question_cond_qn]"]' => ['!value' => '_none'],
        ],
      ];

      $element['subform']['field_quiz_question_cond_answ']["widget"]['#wrapper_attributes'] = ['id' => 'edit-field-quiz-questions-'.$element["#delta"].'-subform-field-quiz-question-cond-answ-container'];

      $element['subform']['field_quiz_question_cond_qn']['widget']['#ajax'] = [
        'callback' => 'answersListCallback',
        'event' => 'change',
        'wrapper'  => 'edit-field-quiz-questions-'.$element["#delta"].'-subform-field-quiz-question-cond-answ-container',
        'method'   => 'replace',
        'progress' => [
          'type' => 'throbber',
        ],
      ];
    }
  }
}

function answersListCallback(&$form, FormStateInterface $form_state) {
  $element = $form_state->getTriggeringElement();
  $field = NestedArray::getValue($form, array_slice($element['#array_parents'], 0, -2));
  return $field["field_quiz_question_cond_answ"]["widget"];
}

/**
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 * @param null $cacheable
 *
 * @return array
 */
function carlson_quiz_allowed_values_function(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = NULL) {
  $options = [];
  if(isset($entity)) {
    $parent = $entity->getParentEntity();
    if(isset($parent) && $parent->hasField('field_quiz_questions') && !empty($parent->get('field_quiz_questions')->getValue())) {
      $questions = $parent->get('field_quiz_questions')->getValue();
      foreach ($questions as $question) {
        if(!empty($question)) {
          $key = $question["target_id"];
          $value = strip_tags(Paragraph::load($question["target_id"])->get('field_quiz_question_text')->value);
          $options[$key] = $value;
        }
      }
    }
    return $options;
  }
}

/**
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 * @param null $cacheable
 *
 * @return array
 */
function carlson_quiz_allowed_values_function_answ(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = NULL) {
  $options = [];
  if(isset($entity)) {
    $parent = $entity->getParentEntity();
    if(isset($parent) && $parent->hasField('field_quiz_questions') && !empty($parent->get('field_quiz_questions')->getValue())) {
      $questions = $parent->get('field_quiz_questions')->getValue();
      foreach ($questions as $question) {
        if(!empty($question)) {
          $question_entity = Paragraph::load($question["target_id"]);
          $answers = $question_entity->get('field_quiz_question_answers')->referencedEntities();
          foreach ($answers as $answer_key => $answer) {
            $answer_id = $answer->id();
            $answer_text = $answer->hasField('field_quiz_answer_text') ? strip_tags($answer->get('field_quiz_answer_text')->value) : '';
            $options[$answer_id] = $answer_text;
          }
        }
      }
    }
  }
  return $options;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for taxonomies.
 *
 * @param $suggestions
 * @param $vars
 * @param $hook
 */
function carlson_quiz_theme_suggestions_taxonomy_term_alter(&$suggestions, $vars, $hook) {
  $suggestions[] = 'taxonomy_term__' . $vars['elements']['#view_mode'];
}

/**
 * Implements hook_preprocess_html().
 *
 * @param $variables
 */
function carlson_quiz_preprocess_html(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $webform_submission = \Drupal::routeMatch()->getParameter('webform_submission');
  if ($node && $node->getType() == 'quiz' && $webform_submission) {
    $variables['attributes']['class'][] = 'page-node-type-quiz-results';
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @param \Drupal\webform\WebformSubmissionInterface $webform_submission
 */
function carlson_quiz_webform_submission_presave(WebformSubmissionInterface &$webform_submission) {
  $webform_id = $webform_submission->hasField('webform_id') ? $webform_submission->get('webform_id')->target_id : null;
  $entity_id = $webform_submission->hasField('entity_id') ? $webform_submission->get('entity_id')->value : null;

  if($webform_id && $entity_id && $webform_id == 'quiz_node_'.$entity_id) {
    $results = [];
    $results_analyze = [];
    $result_ids = [];
    $default_result_ids = [];
    $max_result_ids = [];
//    $cond_result_ids = [];
    $data =  $webform_submission->getData();

    $node = Node::load($entity_id);
    $questions = $node->get('field_quiz_questions')->referencedEntities();
    foreach ($questions as $question_key => $question) {
      $answers = $question->get('field_quiz_question_answers')->referencedEntities();
      $type = $question->hasField('field_quiz_question_type') && $question->get('field_quiz_question_type')->value === 'multiple' ? 'multiple' : 'single';
      $added = [];
      foreach ($answers as $answer_key => $answer) {
        if(isset($answer) && $answer->hasField('field_quiz_answer_result') && !empty($answer->get('field_quiz_answer_result'))) {
          $answer_results = $answer->get('field_quiz_answer_result')->getValue();
          foreach ($answer_results as $answer_result) {
            $id = $answer_result["target_id"];
            if(!in_array($id, $added)) {
              $default_result_ids[$id] = array_key_exists($id, $default_result_ids) ? ++$default_result_ids[$id] : 1;
              $added[] = $id;
            }
          }
        }
      }
    }

    foreach ($data as $key => $pid) {
      if(substr($key, 0, 9) == 'question_' && $pid) {
        if(is_array($pid)) {
          $added = [];
          foreach ($pid as $pid_item) {
            $answer = Paragraph::load($pid_item);
            if(isset($answer) && $answer->hasField('field_quiz_answer_result') && !empty($answer->get('field_quiz_answer_result'))) {
              $answer_results = $answer->get('field_quiz_answer_result')->getValue();
              foreach ($answer_results as $answer_result) {
                $id = $answer_result["target_id"];
                $result_ids[$id] = array_key_exists($id, $result_ids) ? ++$result_ids[$id] : 1;
                if(!in_array($id, $added)) {
                  $max_result_ids[$id] = array_key_exists($id, $max_result_ids) ? ++$max_result_ids[$id] : 1;
                  $added[] = $id;
                }

                //Conditional Results Logic
//                if($answer->hasField('field_quiz_answer_cond_results') && !empty($answer->get('field_quiz_answer_cond_results'))) {
//                  $conditional_results = $answer->get('field_quiz_answer_cond_results')->getValue();
//                  if(!empty($conditional_results) && $conditional_results[0]["value"] == '1') {
//                    $cond_result_ids[$id] = array_key_exists($id, $cond_result_ids) ? ++$cond_result_ids[$id] : 1;
//                  }
//                }
              }
            }
          }
        }
        else {
          $answer = Paragraph::load($pid);
          if(isset($answer) && $answer->hasField('field_quiz_answer_result') && !empty($answer->get('field_quiz_answer_result'))) {
            $answer_results = $answer->get('field_quiz_answer_result')->getValue();
            foreach ($answer_results as $answer_result) {
              $id = $answer_result["target_id"];
              $result_ids[$id] = array_key_exists($id, $result_ids) ? ++$result_ids[$id] : 1;
              $max_result_ids[$id] = array_key_exists($id, $max_result_ids) ? ++$max_result_ids[$id] : 1;

              //Conditional Results Logic
//              if($answer->hasField('field_quiz_answer_cond_results') && !empty($answer->get('field_quiz_answer_cond_results'))) {
//                $conditional_results = $answer->get('field_quiz_answer_cond_results')->getValue();
//                if(!empty($conditional_results) && $conditional_results[0]["value"] == '1') {
//                  $cond_result_ids[$id] = array_key_exists($id, $cond_result_ids) ? ++$cond_result_ids[$id] : 1;
//                }
//              }
            }
          }
        }
      }
    }

//    if(!empty($cond_result_ids)) {
//      $result_ids = $cond_result_ids;
//    }

    $result_ids = array_filter($result_ids, function($v, $k) use ($default_result_ids, $max_result_ids) {
      return $max_result_ids[$k] >= $default_result_ids[$k];
    }, ARRAY_FILTER_USE_BOTH);
    foreach ($result_ids as $tid => $value) {
      $result = Term::load($tid);
      $offset = $result->get('field_sort_weight')->getValue() ? $result->get('field_sort_weight')->getValue()['0']['value'] : 0;
      $result_ids[$tid] = $value - $offset;
    }
    arsort($result_ids);
    $result_ids_to_save = count($result_ids) > 3 ? array_slice($result_ids, 0, 3, true) : $result_ids;

    foreach ($result_ids_to_save as $tid => $value) {
      $result = Term::load($tid);
      $results[] = $result->label();
    }

    foreach ($result_ids as $tid => $value) {
      $result = Term::load($tid);
      $results_analyze[] = $result->label() . ' ' . $value;
    }

    $webform_submission->setElementData('results', implode(",", $results));
    $webform_submission->setElementData('results_analyze', implode(", ", $results_analyze));
  }
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 */
function carlson_quiz_preprocess_paragraph__quiz_conditional_paragraph(&$variables) {
  $webform_submission = \Drupal::routeMatch()->getParameter('webform_submission');
  $paragraph = $variables['paragraph'];
  $show_paragraph = false;
  if($webform_submission && $paragraph->hasField('field_quiz_question_cond_answ') && !empty($paragraph->get('field_quiz_question_cond_answ')->getValue())) {
    $conditional_answers = $paragraph->get('field_quiz_question_cond_answ')->getValue();
    $data =  $webform_submission->getData();
    foreach ($data as $data_item_key => $data_item) {
      if(is_array($data_item)) {
        foreach ($data_item as $data_subitem_key => $data_subitem) {
          $data[$data_item_key.$data_subitem_key] = $data_subitem;
        }
      }
    }
    foreach ($conditional_answers as $conditional_answer) {
      if(in_array($conditional_answer["value"], $data, true)) {
        $show_paragraph = true;
      }
    }
  }
  $variables['show_paragraph'] = $show_paragraph;
}
