<?php

/**
 * @file
 * General functions and hook implementations.
 */

use Drupal\chosen_lib\Hook\ChosenLibHooks;
use Drupal\Core\DrupalKernel;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_library_info_alter().
 */
#[LegacyHook]
function chosen_lib_library_info_alter(array &$libraries, $module) {
  \Drupal::service(ChosenLibHooks::class)->libraryInfoAlter($libraries, $module);
}

/**
 * Get the location of the Chosen library.
 *
 * @return string|false
 *   The location of the library, or FALSE if the library isn't installed.
 */
function _chosen_lib_get_chosen_path() {
  $searchdir = [];

  $searchdir[] = 'profiles/' . \Drupal::installProfile() . '/libraries/';
  $searchdir[] = 'libraries/';
  $searchdir[] = DrupalKernel::findSitePath(\Drupal::request()) . '/libraries/';

  foreach ($searchdir as $dir) {
    $path = $dir . 'chosen';

    if (
      file_exists($path . '/chosen.min.js') ||
      file_exists($path . '/chosen.js')
    ) {
      return $path;
    }
  }

  return FALSE;
}
