menu_injector.menu_injector_rule.*:
  type: config_entity
  label: 'Menu injector rule config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    enabled:
      type: boolean
      label: 'Whether the rule is enabled or not'