menu_injector.menu_injector_rule.*:
  type: config_entity
  label: 'Menu injector rule config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    enabled:
      type: boolean
      label: 'Whether the rule is enabled or not'
    vocab_list:
      type: string
      label: 'The vocabulary list'
    taxonomy_term:
      type: string
      label: 'The taxonomy term'
    parent:
      type: string
      label: 'The parent menu plugin ID used for this rule'
    menu_links:
      type: string
      label: 'The menu links or menu system to inject'
    menu_choice:
      type: string
      label: 'Which menu to inject into'
    menu_mode:
      type: string
      label: 'Which menu mode to use'
    taxonomy_map_field:
      type: string
      label: 'Which taxonomy field to map with'
    content_type:
      type: string
      label: 'Which content type bundle reference'