<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 */
function barrio_carlson_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['barrio_carlson_navbar_top_background']['#options'] = array(
      'bg-primary' => t('Primary'),
      'bg-secondary' => t('Secondary'),
      'bg-light' => t('Light'),
      'bg-dark' => t('Dark'),
      'bg-white' => t('White'),
      'bg-transparent' => t('Transparent'),
  );
  $form['components']['navbar']['barrio_carlson_navbar_background']['#options'] = array(
      'bg-primary' => t('Primary'),
      'bg-secondary' => t('Secondary'),
      'bg-light' => t('Light'),
      'bg-dark' => t('Dark'),
      'bg-white' => t('White'),
      'bg-transparent' => t('Transparent'),
  );

  // Work-around for a core bug affecting admin themes. See issue #943212.
  if (isset($form_id)) {
    return;
  }

  unset($form['logo']);
  $form['theme_settings']['#open'] = FALSE;
  $form['favicon']['default_favicon']['#default_value'] = theme_get_setting('favicon.use_default');
  $form['header_options'] = array(
    '#type' => 'details',
    '#title' => t('Header options'),
    '#open' => TRUE,
  );
  $form['header_options']['campus_select'] = array(
    '#type' => 'radios',
    '#title' => t('Select campus'),
    '#default_value' => theme_get_setting('campus_select'),
    '#options' => array(
      'umnhf-campus-tc' => 'Twin Cities',
      'umnhf-campus-c' => 'Crookston',
      'umnhf-campus-d' => 'Duluth',
      'umnhf-campus-e' => 'Extension',
      'umnhf-campus-m' => 'Morris',
      'umnhf-campus-r' => 'Rochester',
    ),
  );
  $form['header_options']['dtd_select'] = array(
    '#type' => 'radios',
    '#title' => t('Use "Driven to Discover"'),
    '#default_value' => theme_get_setting('dtd_select'),
    '#options' => array(
      'dtd' => t('yes'),
      'no-dtd' => t('no'),
    ),
  );
  $form['header_options']['header_color'] = array(
    '#type' => 'radios',
    '#title' => t('Header background color'),
    '#default_value' => theme_get_setting('header_color'),
    '#options' => array(
      'umnhf-background-maroon' => 'maroon',
      'umnhf-background-gold' => 'gold',
    ),
  );
  $form['header_options']['campus_links'] = array(
    '#type' => 'radios',
    '#title' => t('Use campus links'),
    '#options' => array(
      'no-links' => 'No campus links',
      'links' => 'Include campus links',
    ),
    '#description' => t('Choose whether to include links to system campuses.'),
    '#default_value' => theme_get_setting('campus_links'),
  );
  $form['header_options']['myu_text'] = array(
    '#type' => 'radios',
    '#title' => t('MyU link text'),
    '#description' => t('Header MyU link can be configured to either "MyU: For Students, Faculty, and Staff" or just "MyU"'),
    '#options' => array(
      'sfs' => 'use "For Students, Faculty, and Staff',
      'myu' => 'only use "MyU"',
    ),
    '#default_value' => theme_get_setting('myu_text'),
  );
  $form['header_options']['mobile_search'] = array(
    '#type' => 'radios',
    '#options' => array(
      'dropdown' => 'Dropdown',
      'two-tier' => 'Search box always visible',
    ),
    '#default_value' => theme_get_setting('mobile_search'),
    '#title' => t('Mobile search box setting'),
    '#description' => t('Configure how search appears on small screens - expandable with a dropdown button, or always visible'),
  );

  $form['footer_options'] = array(
    '#type' => 'details',
    '#title' => t('Footer options'),
    '#open' => TRUE,
  );
  $form['footer_options']['privacy_link'] = array(
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('privacy_link'),
    '#title' => 'Privacy link',
    '#description' => t('If you are using an alternative privacy statement, replace http://privacy.umn.edu with the appropriate url (include "http://" if on another site, or an absolute path - begins with "/" - if using a page on this website).'),
  );
  $form['footer_options']['footer_date'] = array(
    '#type' => 'radios',
    '#title' => t('Use "Current as of X" Date?'),
    '#options' => array(
      0 => 'No',
      1 => 'Yes',
    ),
    '#default_value' => theme_get_setting('footer_date'),
  );
}

function barrio_carlson_preprocess_html(&$variables) {

  $home_link = [
    'umnhf-campus-tc' => 'https://twin-cities.umn.edu',
    'umnhf-campus-e' => 'http://www.extension.umn.edu',
    'umnhf-campus-c' => 'https://crk.umn.edu',
    'umnhf-campus-m' => 'https://www4.morris.umn.edu',
    'umnhf-campus-d' => 'https://d.umn.edu',
    'umnhf-campus-r' => 'https://r.umn.edu',
    'umnhf-campus-rso' => 'https://twin-cities.umn.edu',
  ];

  $variables['campus_links'] = theme_get_setting('campus_links');
  $dtd_select = theme_get_setting('dtd_select');
  $variables['myu_text'] = theme_get_setting('myu_text');
  $header_color = theme_get_setting('header_color');
  $variables['campus_header'] = theme_get_setting('campus_select');

  if( isset( $variables['campus_header'] ) ) {
    $variables['home_link'] = $home_link[$variables['campus_header']];
  } else {
    $variables['home_link'] = $home_link['umnhf-campus-tc'];
  }

  $variables['privacy_link'] = theme_get_setting('privacy_link');
  $footer_date = theme_get_setting('footer_date');

  if (!empty($footer_date)) {
    $last_updated_node_array = node_get_recent(1);
    if (!empty($last_updated_node_array)) {
      $last_updated_node = array_shift($last_updated_node_array);
      $variables['last_updated'] = date('F j, Y', $last_updated_node->getRevisionCreationTime());
    }
  }

  $variables['mobile_search'] = theme_get_setting('mobile_search');
  $variables['copyright_year'] = date('Y');
  $current_page_url = \Drupal::Request()->getUri();
  $variables['accessibility_reporting_link'] = \Drupal::config('system.site')->get('accessibility_reporting_script') . "?ref_url=$current_page_url";
  $variables['accessibility_reporting_text'] = \Drupal::config('system.site')->get('accessibility_reporting_text');
  $variables['onestop_link'] = 'https://onestop.umn.edu';

  $header_class_array = array($variables['campus_header'], $dtd_select, $header_color, $variables['mobile_search'], $variables['campus_links']);
  $variables['umn_header_classes'] = implode(' ', $header_class_array);

  $block_manager = \Drupal::service('plugin.manager.block');
  $search_block_instance = $block_manager->createInstance('umn_search_block', array());
  $block_output = $search_block_instance->build();
  $variables['search_block'] = $block_output;

}

/**
* Implements hook_preprocess_node() for NODE document templates.
*/
function barrio_carlson_preprocess_node(&$variables) {
  // Allowed view modes
  $view_mode = $variables['view_mode']; // Retrieve view mode
  $allowed_view_modes = ['full']; // Array of allowed view modes (for performance so as to not execute on unneeded nodes)

  // If view mode is in allowed view modes list, pass to THEME_add_regions_to_node()
  if(in_array($view_mode, $allowed_view_modes)) {
    // Allowed regions (for performance so as to not execute for unneeded region)
    $allowed_regions = ['sticky_sidebar'];
    barrio_carlson_add_regions_to_node($allowed_regions, $variables);
  }
}

/**
* THEME_add_regions_to_node
*/

function barrio_carlson_add_regions_to_node($allowed_regions, &$variables) {
  // Retrieve active theme
  $theme = \Drupal::theme()->getActiveTheme()->getName();

  // Retrieve theme regions
  $available_regions = system_region_list($theme, 'REGIONS_ALL');

  // Validate allowed regions with available regions
  $regions = array_intersect(array_keys($available_regions), $allowed_regions);

  // For each region
  foreach ($regions as $key => $region) {

    // Load region blocks
    $blocks = entity_load_multiple_by_properties('block', array('theme' => $theme, 'region' => $region));

    // Sort ‘em
    uasort($blocks, 'Drupal\block\Entity\Block::sort');

    // Capture viewable blocks and their settings to $build
    $build = array();
    foreach ($blocks as $key => $block) {
      if ($block->access('view')) {
        $build[$key] = entity_view($block, 'block');
      }
    }

    // Add build to region
    $variables[$region] = $build;
  }
}