<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function carlson_megamenu_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.my_module':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module adds two custom layouts (for Layout Builder) with a configuration option for the image location.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme() for registering new field layouts.
 */
function carlson_megamenu_layouts_theme($existing, $type, $theme, $path) {
  return [
    'mega_menu_2_col' => [
      'template' => 'mega-menu-2-col',
      // layout_plugin expects the theme hook to be declared with this:
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    'mega_menu_3_col' => [
      'template' => 'mega-menu-3-col',
      // layout_plugin expects the theme hook to be declared with this:
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    'mega_menu_layout_8_4' => [
      'template' => 'mega-menu-layout-8-4',
      // layout_plugin expects the theme hook to be declared with this:
      'render element' => 'content',
      'base hook' => 'layout',
    ],
  ];
}
