csom_datalayer.settings:
  type: config_object
  mapping:
    status_url:
      type: string
      label: 'Status Web Service URL'
    status_user:
      type: string
      label: 'Status User'
    status_pass:
      type: string
      label: 'Status Password'
    analytics_url:
      type: string
      label: 'Analytics Web Service URL'
    analytics_user:
      type: string
      label: 'Analytics User'
    analytics_pass:
      type: string
      label: 'Analytics Password'