<?php

/**
 * @file
 * Module hooks for Paragraphs Admin module.
 */

use Drupal\paragraphs_admin\Form\ParagraphDeleteForm;

/**
 * Implements hook_views_data_alter().
 */
function paragraphs_admin_views_data_alter(array &$data) {
  $data['paragraphs_item_field_data']['paragraphs_host_entity']['field'] = [
    'title' => t('Host Entity'),
    'help' => t('Displays a link to the top-level host entity for a paragraph.'),
    'id' => 'paragraphs_host_entity',
  ];
}

/**
 * Implements hook_entity_type_build().
 */
function paragraphs_admin_entity_type_build(array &$entity_types) {
  $entity_types['paragraph']->setFormClass('paragraph_delete', ParagraphDeleteForm::class);
}
