<?php

/**
 * @file
 * Primary module hooks for Paragraphs Admin module.
 */

/**
 * Implements hook_views_data_alter().
 */
function paragraphs_admin_views_data_alter(array &$data) {
  $data['paragraphs_item_field_data']['paragraphs_host_entity']['field'] = [
    'title' => t('Host Entity'),
    'help' => t('Displays a link to the top-level host entity for a paragraph.'),
    'id' => 'paragraphs_host_entity',
  ];
}
