_core:
  default_config_hash: MWtaH6iqiztF4V37kZZSpw-NZBbZijdlO_xMPIUCibY
determine_menu: true
disable_admin_page: true
append_current_page: true
current_page_as_link: true
append_member_page: false
member_page_as_link: true
remove_home: false
add_home: true
front_title: 1
exclude_empty_url: true
menu_breadcrumb_menus:
  academics:
    enabled: 1
    weight: -10
    taxattach: 0
    langhandle: 0
  admin:
    enabled: 0
    weight: -9
    taxattach: 0
    langhandle: 0
  executive-education:
    enabled: 1
    weight: -8
    taxattach: 0
    langhandle: 0
  faculty-and-research:
    enabled: 1
    weight: -7
    taxattach: 0
    langhandle: 0
  main:
    enabled: 1
    weight: -6
    taxattach: 0
    langhandle: 0
  footer:
    enabled: 0
    weight: -5
    taxattach: 0
    langhandle: 0
  footer-second:
    enabled: 0
    weight: -4
    taxattach: 0
    langhandle: 0
  tools:
    enabled: 0
    weight: -3
    taxattach: 0
    langhandle: 0
  account:
    enabled: 0
    weight: -2
    taxattach: 0
    langhandle: 0
