<?php

/**
 * @file
 * A module to inline a critical CSS file in HTML head.
 */
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\critical_css\Hook\CriticalCssHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function critical_css_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(CriticalCssHooks::class)->help($route_name, $route_match);
}
