<?php

/**
 * @file
 * Chosen test module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\chosen_test\Hook\ChosenTestHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function chosen_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(ChosenTestHooks::class)->entityBaseFieldInfo($entity_type);
}
