<?php

/**
 * @file
 * Contains carlson_styleguide.module.
 */

/**
 * Implements hook_theme().
 */
function carlson_styleguide_theme() {
  return [
    'test_buttons' => [
      'variables' => [],
      'template' => 'tests/test-buttons',
    ],
    'test_cta_links' => [
      'variables' => [],
      'template' => 'tests/test-cta-links',
    ],
    'test_cta_links_modal' => [
      'variables' => [],
      'template' => 'tests/test-cta-links-modal',
    ],
    'test_typography' => [
      'variables' => [],
      'template' => 'tests/test-typography',
    ],
    'styleguide_index' => [
      'variables' => [
        'styleguide_pages' => [],
      ],
      'template' => 'tests/styleguide-index',
    ],
  ];
}
