<?php

/*
*Implements hook_update_N().
*/

/*can run http://{your_site_name}/update.php to then run this update
 function, just make sure to increase the function number by one each time you whant an update */
/*'primary key' => array('SlateID', 'Program')*/
function CSOM_DataLayer_schema()
{
  $schema = array();
  $schema['csom_slate_status'] = array(
    'description' => t('Table with Slate Data.'),
    'fields' => array(
      'SlateID' => array(
        'description' => t('Slate ID'),
        'type' => 'varchar',
        'length' => 1000,
        'not null' => TRUE,
        'default' => ''),
      'Program' => array(
        'description' => t('Academic Program'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'CurrentStatus' => array(
        'description' => t('Program Status'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'Email' => array(
        'description' => t('Client Email'),
        'type' => 'varchar',
        'length' => 1000,
        'not null' => TRUE,
        'default' => ''),
      'GAClientID' => array(
        'description' => t('Google Analytics Client ID'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'PiwikVisitorID' => array(
        'description' => t('Piwik Analytics Visitor ID'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'Inquiry' => array(
        'description' => t('Inquiry'),
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0),
      'InquiryDate' => array(
        'description' => t('Date of Inquiry Interaction'),
        'mysql_type' => 'DATETIME',
        'not null' => FALSE),
      'InquiryActivities' => array(
        'description' => t('Inquiry Activities'),
        'type' => 'varchar',
        'length' => 4000,
        'not null' => TRUE,
        'default' => ''),
      'Applicant' => array(
        'description' => t('Applicant'),
        'type' => 'int',
        'not null' => TRUE),
      'AppDate' => array(
        'description' => t('Applicant Start Date'),
        'mysql_type' => 'DATETIME',
        'not null' => FALSE),
      'AppTerm' => array(
        'description' => t('Applicant Term'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'AppStatus' => array(
        'description' => t('Applicant Status'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'Inactive' => array(
        'description' => t('Inactive Status Flag'),
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0),
      'InactiveDate' => array(
        'description' => t('Inactive Status Date'),
        'mysql_type' => 'DATETIME',
        'not null' => FALSE),
    ),

    'indexes' => array(
      'visitor' => array('PiwikVisitorID'),
      'ga' => array('GAClientID'),
    ),
  );
  $schema['csom_piwik_status'] = array(

    'description' => t('Shows web analytics collected by Matomo'),
    'fields' => array(
      'SubscriberID' => array(
        'description' => t('Piwik Analytics Subscriber ID'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'PiwikVisitorID' => array(
        'description' => t('Piwik Analytics Visitor ID'),
        'type' => 'varchar',
        'length' => 100,
        'not null' => TRUE,
        'default' => ''),
      'VisitorType' => array(
        'description' => t('Visitor Type'),
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
        'default' => ''),
      'Browser' => array(
        'description' => t('Web Browser'),
        'type' => 'varchar',
        'length' => 150,
        'not null' => FALSE,
        'default' => ''),
      'DeviceType' => array(
        'description' => t('Device Type'),
        'type' => 'varchar',
        'length' => 150,
        'not null' => FALSE,
        'default' => ''),
      'Resolution' => array(
        'description' => t('Resolution'),
        'type' => 'varchar',
        'length' => 150,
        'not null' => FALSE,
        'default' => ''),
      'TotalVisits' => array(
        'description' => t('Total Visits'),
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0),
      'AvgActionsPerVisit' => array(
        'description' => t('Avg Actions per Visit'),
        'type' => 'float',
        'not null' => FALSE),
      'AvgVisitDuration' => array(
        'description' => t('Avg Visit Duration'),
        'type' => 'float',
        'not null' => FALSE),
      'DaysSinceLastVisit' => array(
        'description' => t('Days Since Last Visit'),
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0),
      'FirstActionDate' => array(
        'description' => t('First Action Date'),
        'mysql_type' => 'DATETIME',
        'not null' => FALSE),
      'LastActionDate' => array(
        'description' => t('Last Action Date'),
        'mysql_type' => 'DATETIME',
        'not null' => FALSE),
      'LastLocation' => array(
        'description' => t('Last Visitor Location'),
        'type' => 'varchar',
        'length' => 500,
        'not null' => FALSE,
        'default' => ''),
      'LastReferrerUrl' => array(
        'description' => t('Last Referrer Url'),
        'type' => 'varchar',
        'length' => 2000,
        'not null' => FALSE,
        'default' => ''),
      'LastCampaignSource' => array(
        'description' => t('Last Campaign Source'),
        'type' => 'varchar',
        'length' => 500,
        'not null' => FALSE,
        'default' => ''),
      'LastCampaignName' => array(
        'description' => t('Last Campaign Name'),
        'type' => 'varchar',
        'length' => 500,
        'not null' => FALSE,
        'default' => ''),
      'LastCampaignMedium' => array(
        'description' => t('Last Campaign Medium'),
        'type' => 'varchar',
        'length' => 500,
        'not null' => FALSE,
        'default' => ''),
      'LastCampaignContent' => array(
        'description' => t('Last Campaign Content'),
        'type' => 'varchar',
        'length' => 500,
        'not null' => FALSE,
        'default' => ''),
    ),

    'indexes' => array(
      'visitor' => array( 'PiwikVisitorID'),

    ),

    'primary key' => array ('PiwikVisitorID' )
  );

  return $schema;
}