# Schema for the views cache.
views.cache.custom_tag:
  type: mapping
  label: 'Custom tag cache'
  mapping:
    type:
      type: string
      label: 'Cache type'
    options:
      type: mapping
      label: 'Custom tag options'
      mapping:
        custom_tag:
          type: string
          label: 'Custom tag list'
        custom_tag_output_lifespan:
          type: string
          label: 'The fixed output lifespan or custom if the relative expression should be used'
        custom_tag_output_lifespan_expression:
          type: string
          label: 'Expression used in strtotime().'
