default_education_abroad_fields.settings:
  type: config_object
  label: 'Default Education Abroad Fields settings'
  mapping:
    field_ea_program_objective:
      type: mapping
      label: 'Program Objective'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
    field_ea_program_housing_food:
      type: mapping
      label: 'Housing/Food'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
    field_ea_program_academics:
      type: mapping
      label: 'Academics and Credits'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
    field_visa_and_passport:
      type: mapping
      label: 'Visa and Passport'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
    field_ea_program_app_admission:
      type: mapping
      label: 'Application and Admissions'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
    field_ea_program_aid_scholarhips:
      type: mapping
      label: 'Financial Aid and Scholarship'
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: string
          label: 'Text format'
