<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function bootstrap_carlson_preprocess_html(&$variables) {

  $home_link = [
    'umnhf-campus-tc' => 'https://twin-cities.umn.edu',
    'umnhf-campus-e' => 'http://www.extension.umn.edu',
    'umnhf-campus-c' => 'https://crk.umn.edu',
    'umnhf-campus-m' => 'https://www4.morris.umn.edu',
    'umnhf-campus-d' => 'https://d.umn.edu',
    'umnhf-campus-r' => 'https://r.umn.edu',
    'umnhf-campus-rso' => 'https://twin-cities.umn.edu',
  ];

  $variables['campus_links'] = theme_get_setting('campus_links');
  $dtd_select = theme_get_setting('dtd_select');
  $variables['myu_text'] = theme_get_setting('myu_text');
  $header_color = theme_get_setting('header_color');
  $variables['campus_header'] = theme_get_setting('campus_select');
  $variables['home_link'] = $home_link[$variables['campus_header']];
  $variables['privacy_link'] = theme_get_setting('privacy_link');
  $footer_date = theme_get_setting('footer_date');

  if (!empty($footer_date)) {
    $last_updated_node_array = node_get_recent(1);
    if (!empty($last_updated_node_array)) {
      $last_updated_node = array_shift($last_updated_node_array);
      $variables['last_updated'] = date('F j, Y', $last_updated_node->getRevisionCreationTime());
    }
  }

  $variables['mobile_search'] = theme_get_setting('mobile_search');
  $variables['copyright_year'] = date('Y');
  $current_page_url = \Drupal::Request()->getUri();
  $variables['accessibility_reporting_link'] = \Drupal::config('system.site')->get('accessibility_reporting_script') . "?ref_url=$current_page_url";
  $variables['accessibility_reporting_text'] = \Drupal::config('system.site')->get('accessibility_reporting_text');
  $variables['onestop_link'] = 'https://onestop.umn.edu';

  $header_class_array = array($variables['campus_header'], $dtd_select, $header_color, $variables['mobile_search'], $variables['campus_links']);
  $variables['umn_header_classes'] = implode(' ', $header_class_array);

  $block_manager = \Drupal::service('plugin.manager.block');
  $search_block_instance = $block_manager->createInstance('umn_search_block', array());
  $block_output = $search_block_instance->build();
  $variables['search_block'] = $block_output;

}
